# Generated by Django 4.1.6 on 2023-02-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_appointment_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
