# Generated by Django 4.1.6 on 2023-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
